
pull_request_rules:
  - name: ownership check
    conditions:
      - base=main
      # Frontend ownership rule
      - or:
        - "-files~=^frontend/.*"
        - and:
          - "files~=^frontend/.*"
          - or:
            - author=@ownership-frontend
            - approved-reviews-by=@ownership-frontend
      # Backend ownership rule
      - or:
        - "-files~=^backend/.*"
        - and:
          - "files~=^backend/.*"
          - author=@ownership-backend
          - approved-reviews-by=@ownership-backend
    actions:
      post_check:
        summary: ownership

  - name: ownership approval
    conditions:
      - "check-success=Rule: ownership check (post_check)"
    actions:
      review:
        type: APPROVE
        bot_account: ownership-review

  - name: ownership approval
    conditions:
      - "check-failure=Rule: ownership check (post_check)"
    actions:
      review:
        type: REQUEST_CHANGES
        bot_account: ownership-review

  - name: readability check
    conditions:
      - base=main
      # Python readability
      - or:
        - "-files~=.*/.py"
        - and:
          - "files~=.*/.py"
          - or:
            - author=@readability-python
            - approved-reviews-by=@readability-python
      # JS readability
      - or:
        - "-files~=.*/.js"
        - and:
          - "files~=.*/.js"
          - or:
            - author=@readability-js
            - approved-reviews-by=@readability-js
    actions:
      post_check:
        summary: readability

  - name: readability approval
    conditions:
      - "check-success=Rule: readability check (post_check)"
    actions:
      review:
        type: APPROVE
        bot_account: readability-review


  - name: readability dismiss
    conditions:
      - "check-failure=Rule: readability check (post_check)"
    actions:
      review:
        type: REQUEST_CHANGES
        bot_account: readability-review
