pull_request_rules:
  - name: ownership check
    conditions:
      - base=main
      - approved-reviews-by=@ownership
      # Frontend ownership rule
      - or:
        - "-files~=^frontend/.*"
        - and:
          - author=@ownership-frontend
          - label=self-review-frontend
        - approved-reviews-by=@ownership-frontend
      # Backend ownership rule
      - or:
        - "-files~=^backend/.*"
        - and:
          - author=@ownership-backend
          - label=self-review-backend
        - approved-reviews-by=@ownership-backend
    actions:
      post_check:
        summary: ownership

  - name: ownership approval
    conditions:
      - "check-success=Rule: ownership check (post_check)"
    actions:
      review:
        type: APPROVE
        bot_account: ownership-review

  - name: ownership dismiss
    conditions:
      - "check-failure=Rule: ownership check (post_check)"
    actions:
      review:
        type: REQUEST_CHANGES
        bot_account: ownership-review

  - name: readability check
    conditions:
      - base=main
      - approved-reviews-by=@readability
      # Python readability
      - or:
        - "-files~=.*/.py"
        - and:
          - author=@readability-python
          - label=self-review-python
        - approved-reviews-by=@readability-python
      # JS readability
      - or:
        - "-files~=.*/.js"
        - and:
          - author=@readability-js
          - label=self-review-js
        - approved-reviews-by=@readability-js
    actions:
      post_check:
        summary: readability

  - name: readability approval
    conditions:
      - "check-success=Rule: readability check (post_check)"
    actions:
      review:
        type: APPROVE
        bot_account: readability-review

  - name: readability dismiss
    conditions:
      - "check-failure=Rule: readability check (post_check)"
    actions:
      review:
        type: REQUEST_CHANGES
        bot_account: readability-review
